
services:
  cstoken:
    container_name: cstoken
    image: cstoken:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    # develop:
    #   watch:
    #     - path: src/
    #       action: sync
    #       target: /app/src
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: ${CSTOKEN_DATABASE_URL}
      PORT: '3002'      
      RABBIT_HOST: ${CSTOKEN_RABBIT_HOST}
      RABBIT_USER: ${CSTOKEN_RABBIT_USER}
      RABBIT_PASS: ${CSTOKEN_RABBIT_PASS}
      RABBIT_QUEUE: ${CSTOKEN_RABBIT_QUEUE}
      DEBUG: "AMQPPubSub"
    ports:
      - '3002:3002'
    networks:
      - cstoken-network
    depends_on:
      cstokenDB:
        condition: service_started
      rabbitMQ:
        condition: service_healthy

      
  cstokenDB:
    container_name: cstokenDB
    #platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:13.6
    environment:
      POSTGRES_USER: ${CSTOKEN_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${CSTOKEN_DATABASE_PASSWORD}
      POSTGRES_DB: ${CSTOKEN_DATABASE_NAME}
    volumes:
      - cstoken-data:/var/lib/postgresql/data/ #using a volume

    ports:
      - '5435:5432'
    networks:
      - cstoken-network

  rabbitMQ:
    container_name: rabbitMQ
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 30s
      retries: 10    
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq      
    networks:
      - cstoken-network

volumes:
  cstoken-data:

networks:
  cstoken-network:
    name: CSToken
    driver: bridge