
services:
  auth:
    container_name: auth
    image:  auth:v1.0
    env_file: .env
    ports:
      - 3001:3001
    environment:
      PORT: ${AUTH_PORT}
      MONGO_URI: ${AUTH_MONGO_URI}
      DOCTYPE: ${AUTH_DOCTYPE}
      JWT_KEY: ${AUTH_JWT_KEY}
      AWS_ACCESS_KEY_ID: ${AUTH_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AUTH_AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AUTH_AWS_DEFAULT_REGION}
      WHITELIST_CORS: ${AUTH_WHITELIST_CORS}

  cstoken:
    container_name: cstoken
    image: cstoken-dev:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: ${CSTOKEN_DATABASE_URL}
      PORT: '3002'      
      REDIS_HOST: ${CSTOKEN_REDIS_HOST}
      REDIS_PORT: ${CSTOKEN_REDIS_PORT}
      REDIS_PASS: ${CSTOKEN_REDIS_PASS}
      JWT_SECRET: ${CSTOKEN_JWT_SECRET}
      WHITELIST_CORS: ${CSTOKEN_WHITELIST_CORS}
    ports:
      - '3002:3002'
    networks:
      - cstoken-network
    depends_on:
      cstokenDB:
        condition: service_started
      cache:
        condition: service_healthy

      
  cstokenDB:
    container_name: cstokenDB
    #platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:13.6
    environment:
      POSTGRES_USER: ${CSTOKEN_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${CSTOKEN_DATABASE_PASSWORD}
      POSTGRES_DB: ${CSTOKEN_DATABASE_NAME}
    volumes:
      - cstoken-data:/var/lib/postgresql/data/ #using a volume

    ports:
      - '5435:5432'
    networks:
      - cstoken-network

  ttt:
    container_name: ttt
    image: ttt-dev:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: ${TTT_DATABASE_URL}
      PORT: '3008'      
      REDIS_HOST: ${CSTOKEN_REDIS_HOST}
      REDIS_PORT: ${CSTOKEN_REDIS_PORT}
      REDIS_PASS: ${CSTOKEN_REDIS_PASS}
    ports:
      - '3008:3008'
    networks:
      - cstoken-network
    depends_on:
      tttDB:
        condition: service_started
      cache:
        condition: service_healthy

  tttDB:
    container_name: tttDB
    #platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:13.6
    environment:
      POSTGRES_USER: ${TTT_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${TTT_DATABASE_PASSWORD}
      POSTGRES_DB: ${TTT_DATABASE_NAME}
    volumes:
      - ttt-data:/var/lib/postgresql/data/ #using a volume

    ports:
      - '5438:5432'
    networks:
      - cstoken-network

  cache:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${CSTOKEN_REDIS_PASS}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s
    volumes: 
      - cache:/data
    networks:
      - cstoken-network

volumes:
  cstoken-data:
  cache:
  ttt-data:

networks:
  cstoken-network:
    name: CSToken
    driver: bridge